baseURL = 'https://alexbhasin.ca'
languageCode = 'en-us'
title = 'Alexander Bhasin'
disableKinds = ["taxonomy", "term"]

[menu]
[[menu.main]]
  identifier = 'home'
  name = 'home'
  title = 'Alexander Bhasin | home'
  url = '/'
  weight = 10
[[menu.main]]
  identifier = 'posts'
  name = 'posts'
  title = 'Alexander Bhasin | posts'
  url = '/posts/'
  weight = 20
  
[[menu.socials]]
  name = 'github'
  url = 'https://github.com/alexbhas'
  weight = 10
[[menu.socials]]
  name = 'linkedin'
  url = 'https://www.linkedin.com/in/alexbhas/'
  weight = 20


[params]
  description = 'Software Developer'
  images = ['favicon.png']
  title = 'Alexander Bhasin'

[outputs]
  home = ['html']
